# Copyright (c) 2017 YCSB contributors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License. See accompanying
# LICENSE file.

# Core YCSB properties.
table = usertable
zeropadding=20
requestdistribution=zipfian
insertorder=ordered

# Cloud Spanner properties
cloudspanner.experimentalhost = http://spanner.spanner-ns:15000
cloudspanner.project = default
cloudspanner.instance = default
cloudspanner.database = ycsbdb

cloudspanner.readmode = read
cloudspanner.boundedstaleness = 0
cloudspanner.batchinserts = 1

cloudspanner.dynamicchannelpool.enabled=true
cloudspanner.dynamicchannelpool.initsize=1
cloudspanner.dynamicchannelpool.minsize=1
cloudspanner.dynamicchannelpool.maxsize=256
# Optional: override grpc-gcp dynamic scaling thresholds. If unset, Spanner defaults are used.
cloudspanner.dynamicchannelpool.minrpcperchannel=5
cloudspanner.dynamicchannelpool.maxrpcperchannel=90
threadcount=256

cloudspanner.useplaintext=true
