# this could be changed to a file or other log output
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=FINEST
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tF %1$tT.%1$tL [%4$s] %3$s - %5$s%6$s%n

# Enable FINE logging for bypass routing code path
com.google.cloud.spanner.spi.v1.KeyAwareChannel.level=FINE
com.google.cloud.spanner.spi.v1.ChannelFinder.level=FINE
com.google.cloud.spanner.spi.v1.KeyRangeCache.level=FINE
com.google.cloud.spanner.spi.v1.KeyRecipeCache.level=FINE
com.google.cloud.spanner.spi.v1.GrpcChannelEndpointCache.level=FINE

io.grpc.ChannelLogger.level=FINEST
com.google.cloud.grpc.GcpManagedChannel.level=FINEST
com.google.cloud.grpc.GcpManagedChannelBuilder.level=FINEST

com.google.cloud.spanner.spi.v1.GapicSpannerRpc.level=FINER
io.grpc.level=FINEST
## exclude extremely verbose/per rpc log messages
io.grpc.netty.NettyClientHandler.level=INFO

