apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spanner-ns
  name: irahul-stale-read-directaccess-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irahul-stale-read-directaccess-affinity
  template:
    metadata:
      labels:
        app: irahul-stale-read-directaccess-affinity
    spec:
      containers:
        - name: stale-read-directaccess-affinity
          image: us-central1-docker.pkg.dev/span-cloud-testing/irahul-images/irahul-client:release-use-channel-affinity
          imagePullPolicy: Always
          command: ["java"]
          args:
            - -Xms300m
            - -Xmx300m
            - -XX:-TieredCompilation
            - -XX:CompileThreshold=1000
            - -jar
            - /app/main.jar
          resources:
            requests:
              memory: "400Mi"
              cpu: "1"
            limits:
              memory: "400Mi"
              cpu: "1"
          env:
            - name: PROBE_TYPE
              value: "stale_read"
            - name: QPS
              value: "400"
            - name: MAX_INFLIGHT
              value: "512"
            - name: OTEL_SERVICE_NAME
              value: "irahul-stale-read-directaccess-affinity"
            - name: OTEL_TRACE_SAMPLING_FRACTION
              value: "0"
            - name: GOOGLE_SPANNER_ENABLE_DIRECT_ACCESS
              value: "true"
