apiVersion: batch/v1
kind: Job
metadata:
  namespace: spanner-ns
  name: ycsb-java-run
  labels:
    app: ycsb-java-run
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: ycsb-java-run
    spec:
      restartPolicy: Never
      containers:
        - name: ycsb-client
          image: us-west1-docker.pkg.dev/outbound-flight/spanner-box/ycsb-client:latest
          imagePullPolicy: Always
          args:
            - run
            - cloudspanner
            - -P
            - workloads/workloadb
            - -P
            - cloudspanner/conf/cloudspanner.properties
            - -p
            - recordcount=1000000000
            - -p
            - zeropadding=12
            - -p
            - insertorder=ordered
            - -p
            - operationcount=1000000000000
            - -p
            - maxexecutiontime=180000
            - -threads
            - "50"
            - -s
          resources:
            requests:
              cpu: "7"
              memory: 25Gi
            limits:
              cpu: "7"
              memory: 25Gi
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xms16g -Xmx16g -XX:+AlwaysPreTouch -XX:+UseG1GC
